[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bricks = "DdoHZCPsMoQmRu7LtkvrVfu6TDR9PYJafKxps5cuh4uU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
